baseURL = "https://chechannel.com/"
enableRobotsTXT = "true"
languageCode = "ru-ru"
theme = "antler"
title = "CheChannel"
googleAnalytics = "UA-115874519-1"
copyright = "© 2017-{year} CheChannel"

[params]
  subtitle = "наши путевые заметки"
  email = "hello@chechannel.com"
  sectionsOnIndex = ["post"]
  description = "Мы — Стася, Илья и Ева, семья из трёх человек. Переехали из Санкт-Петербурга в Гданьск. Ведём блог о Польше и нашем быте"

[permalinks]
  posts = "/:slug/"

[params.opengraph.facebook]
  appid = "305800963469106"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.1

[taxonomies]
  tag = "tags"