baseURL = "https://chechannel.com"
enableEmoji = "true"
enableRobotsTXT = "true"
languageCode = "ru-ru"
theme = "antler"
title = "CheChannel"
googleAnalytics = "UA-115874519-1"

[params]
subtitle = "наши путевые заметки"
email = "hello@chechannel.com"
logo = "https://i.imgur.com/nvAWNxH.png"

[permalinks]
post = "/:slug/"
