baseURL = "https://chechannel.com/"
enableRobotsTXT = "true"
languageCode = "ru-ru"
theme = "antler"
title = "CheChannel"
googleAnalytics = "UA-115874519-1"

[params]
    subtitle = "наши путевые заметки"
    email = "hello@chechannel.com"
    logo = "https://i.imgur.com/nvAWNxH.png"

[permalinks]
    posts = "/:slug/"
