---
upload_path: "/static/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
  post:
    default_front_matter_template: 81179d6f-f7fc-4297-88b4-d8b02ab6a97c
version: 0.31.1
