---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
  content/post:
    default_front_matter_template: 81179d6f-f7fc-4297-88b4-d8b02ab6a97c
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: 0.31.1
